const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
const FETCH_MOVIES_BY_KEYWORD = 'FETCH_MOVIES_BY_KEYWORD';
const LOADING_UI = 'LOADING_UI';
const SET_ERRORS = 'SET_ERRORS';
const STOP_LOADING_UI = 'STOP_LOADING_UI';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const CHANGE_PAGE = 'CHANGE_PAGE';
const FILTER_BY = 'FILTER_BY'

export {
    FETCH_POPULAR_MOVIES,
    FETCH_MOVIES_BY_KEYWORD,
    LOADING_UI,
    SET_ERRORS,
    STOP_LOADING_UI,
    CLEAR_ERRORS,
    CHANGE_PAGE,
    FILTER_BY
};