const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
const FETCH_MOVIES_BY_KEYWORD = 'FETCH_MOVIES_BY_KEYWORD';
const LOADING_UI = 'LOADING_UI';
const SET_ERRORS = 'SET_ERRORS';
const STOP_LOADING_UI = 'STOP_LOADING_UI';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const FILTER_BY = 'FILTER_BY';
const KEYWORD = 'KEYWORD';
const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';

export {
  FETCH_POPULAR_MOVIES,
  FETCH_MOVIES_BY_KEYWORD,
  LOADING_UI,
  SET_ERRORS,
  STOP_LOADING_UI,
  CLEAR_ERRORS,
  FILTER_BY,
  KEYWORD,
  FETCH_MOVIE_DETAILS
};
